# Generated by Django 5.0.6 on 2026-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expensegroup',
            new_name='groups_expe_name_a0de89_idx',
            old_name='groups_expen_name_5b2f83_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='groups_grou_group_i_c42577_idx',
            old_name='groups_group_group_i_6756d9_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='groups_grou_group_i_3d0c7c_idx',
            old_name='groups_group_group_i_e8cb94_idx',
        ),
    ]
