from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("groups", "0001_initial"), ("imports", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency", models.CharField(max_length=3)),
                ("effective_date", models.DateField()),
                ("rate_to_inr", models.DecimalField(decimal_places=4, max_digits=12)),
                ("source", models.CharField(default="manual", max_length=160)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"ordering": ["currency", "effective_date"], "unique_together": {("currency", "effective_date")}},
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("original_amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                ("amount_in_inr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("split_type", models.CharField(choices=[("equal", "Equal"), ("unequal", "Unequal"), ("percentage", "Percentage"), ("share", "Share")], max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("needs_review", "Needs review"), ("approved", "Approved"), ("rejected", "Rejected")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exchange_rate", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="expenses.currencyrate")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="groups.expensegroup")),
                ("import_row", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expense", to="imports.importrow")),
                ("payer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="paid_expenses", to="groups.person")),
            ],
            options={"ordering": ["-date", "description"]},
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("original_amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("amount_in_inr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("status", models.CharField(choices=[("needs_review", "Needs review"), ("approved", "Approved"), ("rejected", "Rejected")], default="approved", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exchange_rate", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="expenses.currencyrate")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="settlements", to="groups.expensegroup")),
                ("import_row", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="settlement", to="imports.importrow")),
                ("paid_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlements_paid", to="groups.person")),
                ("paid_to", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlements_received", to="groups.person")),
            ],
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="ExpenseSplit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_in_inr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("raw_value", models.CharField(blank=True, max_length=80)),
                ("membership_valid", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("expense", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="splits", to="expenses.expense")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expense_splits", to="groups.person")),
            ],
            options={"unique_together": {("expense", "person")}},
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("kind", models.CharField(choices=[("expense_payment", "Expense payment"), ("expense_share", "Expense share"), ("settlement_paid", "Settlement paid"), ("settlement_received", "Settlement received")], max_length=40)),
                ("amount_in_inr", models.DecimalField(decimal_places=2, max_digits=14)),
                ("memo", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expense", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="expenses.expense")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="groups.expensegroup")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="groups.person")),
                ("settlement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="expenses.settlement")),
            ],
            options={"ordering": ["date", "id"]},
        ),
        migrations.AddIndex(model_name="currencyrate", index=models.Index(fields=["currency", "effective_date"], name="expenses_cu_currenc_7b4d08_idx")),
        migrations.AddIndex(model_name="expense", index=models.Index(fields=["group", "date"], name="expenses_ex_group_i_bf1c97_idx")),
        migrations.AddIndex(model_name="expense", index=models.Index(fields=["payer", "date"], name="expenses_ex_payer_i_743e2a_idx")),
        migrations.AddIndex(model_name="expense", index=models.Index(fields=["status"], name="expenses_ex_status_5e47ab_idx")),
        migrations.AddIndex(model_name="settlement", index=models.Index(fields=["group", "date"], name="expenses_se_group_i_771b95_idx")),
        migrations.AddIndex(model_name="settlement", index=models.Index(fields=["paid_by", "paid_to"], name="expenses_se_paid_by_caf2df_idx")),
        migrations.AddIndex(model_name="expensesplit", index=models.Index(fields=["person"], name="expenses_ex_person__4c5bd4_idx")),
        migrations.AddIndex(model_name="expensesplit", index=models.Index(fields=["expense", "person"], name="expenses_ex_expense_e7eab5_idx")),
        migrations.AddIndex(model_name="ledgerentry", index=models.Index(fields=["group", "person"], name="expenses_le_group_i_e03482_idx")),
        migrations.AddIndex(model_name="ledgerentry", index=models.Index(fields=["group", "date"], name="expenses_le_group_i_d1d6ab_idx")),
        migrations.AddIndex(model_name="ledgerentry", index=models.Index(fields=["expense"], name="expenses_le_expense_27f756_idx")),
        migrations.AddIndex(model_name="ledgerentry", index=models.Index(fields=["settlement"], name="expenses_le_settlem_6f72ea_idx")),
        migrations.AddConstraint(model_name="settlement", constraint=models.CheckConstraint(check=models.Q(("paid_by", models.F("paid_to")), _negated=True), name="settlement_not_self")),
        migrations.AddConstraint(model_name="ledgerentry", constraint=models.CheckConstraint(check=models.Q(models.Q(("expense__isnull", False), ("settlement__isnull", True)), models.Q(("expense__isnull", True), ("settlement__isnull", False)), _connector="OR"), name="ledger_has_one_source")),
    ]
