# Generated by Django 5.0.6 on 2026-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyrate',
            new_name='expenses_cu_currenc_8e020c_idx',
            old_name='expenses_cu_currenc_7b4d08_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_group_i_f6bb8c_idx',
            old_name='expenses_ex_group_i_bf1c97_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_payer_i_515c6d_idx',
            old_name='expenses_ex_payer_i_743e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_status_cbb790_idx',
            old_name='expenses_ex_status_5e47ab_idx',
        ),
        migrations.RenameIndex(
            model_name='expensesplit',
            new_name='expenses_ex_person__cc0b7e_idx',
            old_name='expenses_ex_person__4c5bd4_idx',
        ),
        migrations.RenameIndex(
            model_name='expensesplit',
            new_name='expenses_ex_expense_48222c_idx',
            old_name='expenses_ex_expense_e7eab5_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='expenses_le_group_i_c63f33_idx',
            old_name='expenses_le_group_i_e03482_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='expenses_le_group_i_224dda_idx',
            old_name='expenses_le_group_i_d1d6ab_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='expenses_le_expense_2a1ad1_idx',
            old_name='expenses_le_expense_27f756_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='expenses_le_settlem_5c3890_idx',
            old_name='expenses_le_settlem_6f72ea_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='expenses_se_group_i_4d6f1b_idx',
            old_name='expenses_se_group_i_771b95_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='expenses_se_paid_by_a9cc8b_idx',
            old_name='expenses_se_paid_by_caf2df_idx',
        ),
    ]
