# Generated by Django 5.0.6 on 2026-06-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importanomaly',
            new_name='imports_imp_batch_i_d321fc_idx',
            old_name='imports_imp_batch_i_c4d1ef_idx',
        ),
        migrations.RenameIndex(
            model_name='importanomaly',
            new_name='imports_imp_categor_77889e_idx',
            old_name='imports_imp_categor_242f59_idx',
        ),
        migrations.RenameIndex(
            model_name='importrow',
            new_name='imports_imp_batch_i_d2e5f6_idx',
            old_name='imports_imp_batch_i_7b1c42_idx',
        ),
    ]
