import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate } from "react-router-dom";
import { ArrowRightLeft, FileWarning, Home, LogOut, ReceiptText, Scale, UsersRound, WalletCards } from "lucide-react";
import "./styles.css";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000/api";

type ApiOptions = RequestInit & { auth?: boolean };

async function api(path: string, options: ApiOptions = {}) {
  const token = localStorage.getItem("access");
  const headers = new Headers(options.headers);
  if (!(options.body instanceof FormData)) headers.set("Content-Type", "application/json");
  if (options.auth !== false && token) headers.set("Authorization", `Bearer ${token}`);
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers });
  if (!response.ok) throw new Error(await response.text());
  return response.json();
}

function formatMoney(value: string | number) {
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value || 0));
}

function Shell({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate();
  const logout = () => {
    localStorage.removeItem("access");
    localStorage.removeItem("refresh");
    navigate("/login");
  };
  const nav = [
    ["/", Home, "Dashboard"],
    ["/imports", FileWarning, "Imports"],
    ["/members", UsersRound, "Members"],
    ["/expenses", ReceiptText, "Expenses"],
    ["/settlements", ArrowRightLeft, "Settlements"],
  ] as const;
  return (
    <div className="shell">
      <aside className="sidebar">
        <div className="brand"><Scale size={22} /> Split Audit</div>
        <nav>
          {nav.map(([to, Icon, label]) => (
            <Link key={to} to={to}><Icon size={18} /> {label}</Link>
          ))}
        </nav>
        <button className="ghost" onClick={logout}><LogOut size={17} /> Logout</button>
      </aside>
      <main>{children}</main>
    </div>
  );
}

function Login() {
  const [username, setUsername] = React.useState("demo");
  const [password, setPassword] = React.useState("demo12345");
  const [error, setError] = React.useState("");
  const navigate = useNavigate();
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setError("");
    try {
      const data = await api("/auth/token/", { method: "POST", auth: false, body: JSON.stringify({ username, password }) });
      localStorage.setItem("access", data.access);
      localStorage.setItem("refresh", data.refresh);
      navigate("/");
    } catch {
      setError("Login failed. Run seed_assignment or create a user.");
    }
  }
  return (
    <div className="login">
      <form onSubmit={submit} className="panel narrow">
        <h1>Shared Expenses Audit</h1>
        <label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} /></label>
        <label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>
        {error && <p className="error">{error}</p>}
        <button type="submit">Sign in</button>
      </form>
    </div>
  );
}

function useLoad<T>(path: string, fallback: T) {
  const [data, setData] = React.useState<T>(fallback);
  const [error, setError] = React.useState("");
  React.useEffect(() => {
    api(path).then(setData).catch((err) => setError(String(err)));
  }, [path]);
  return { data, error, reload: () => api(path).then(setData) };
}

function Dashboard() {
  const { data } = useLoad<any>("/groups/", []);
  const group = data[0];
  const balances = useLoad<any>(group ? `/balances/?group=${group.id}` : "/health/", { balances: [], suggested_settlements: [] });
  return (
    <Shell>
      <header><h1>Group Balances</h1><p>Every number is derived from ledger entries generated by approved expenses and settlements.</p></header>
      <section className="grid two">
        <div className="panel">
          <h2><WalletCards size={20} /> Net position</h2>
          <table><tbody>{balances.data.balances?.map((b: any) => <tr key={b.person}><td>{b.person}</td><td className={Number(b.balance) >= 0 ? "positive" : "negative"}>{formatMoney(b.balance)}</td></tr>)}</tbody></table>
        </div>
        <div className="panel">
          <h2><ArrowRightLeft size={20} /> Suggested settlements</h2>
          <table><tbody>{balances.data.suggested_settlements?.map((s: any, i: number) => <tr key={i}><td>{s.from} pays {s.to}</td><td>{formatMoney(s.amount_in_inr)}</td></tr>)}</tbody></table>
        </div>
      </section>
      <Ledger groupId={group?.id} />
    </Shell>
  );
}

function Ledger({ groupId }: { groupId?: number }) {
  const { data } = useLoad<any[]>(groupId ? `/balances/ledger/?group=${groupId}` : "/health/", []);
  return (
    <section className="panel">
      <h2>Trace ledger</h2>
      <table>
        <thead><tr><th>Date</th><th>Person</th><th>Kind</th><th>Memo</th><th>Amount</th></tr></thead>
        <tbody>{Array.isArray(data) && data.map((entry) => <tr key={entry.id}><td>{entry.date}</td><td>{entry.person_name}</td><td>{entry.kind}</td><td>{entry.memo}</td><td>{formatMoney(entry.amount_in_inr)}</td></tr>)}</tbody>
      </table>
    </section>
  );
}

function Imports() {
  const [file, setFile] = React.useState<File | null>(null);
  const batches = useLoad<any[]>("/imports/", []);
  async function upload() {
    if (!file) return;
    const form = new FormData();
    form.append("file", file);
    await api("/imports/", { method: "POST", body: form });
    batches.reload();
  }
  async function resolve(batchId: number, anomalyId: number) {
    await api(`/imports/${batchId}/resolve/`, { method: "POST", body: JSON.stringify({ anomaly_id: anomalyId, status: "approved" }) });
    batches.reload();
  }
  async function commit(batchId: number) {
    await api(`/imports/${batchId}/commit/`, { method: "POST" });
    batches.reload();
  }
  return (
    <Shell>
      <header><h1>CSV Import Review</h1><p>Rows are parsed first, anomalies are reviewed second, and only approved rows affect balances.</p></header>
      <section className="panel toolbar">
        <input type="file" accept=".csv" onChange={(e) => setFile(e.target.files?.[0] ?? null)} />
        <button onClick={upload}>Upload CSV</button>
      </section>
      {batches.data.map((batch: any) => (
        <section className="panel" key={batch.id}>
          <div className="section-title"><h2>{batch.source_filename}</h2><button onClick={() => commit(batch.id)}>Commit approved rows</button></div>
          <p>{batch.total_rows} rows, {batch.anomaly_count} anomalies, {batch.committed_rows} committed, {batch.skipped_rows} skipped</p>
          <table>
            <thead><tr><th>Row</th><th>Category</th><th>Severity</th><th>Description</th><th>Action</th></tr></thead>
            <tbody>{batch.rows.flatMap((row: any) => row.anomalies.map((a: any) => <tr key={a.id}><td>{a.row_number}</td><td>{a.category}</td><td><span className={`badge ${a.severity}`}>{a.severity}</span></td><td>{a.description}</td><td>{a.approval_required && a.status === "open" ? <button onClick={() => resolve(batch.id, a.id)}>Approve</button> : a.status}</td></tr>))}</tbody>
          </table>
        </section>
      ))}
    </Shell>
  );
}

function SimpleList({ title, path }: { title: string; path: string }) {
  const { data } = useLoad<any[]>(path, []);
  return (
    <Shell>
      <header><h1>{title}</h1></header>
      <section className="panel">
        <table><tbody>{data.map((item: any) => <tr key={item.id}><td>{item.display_name ?? item.description ?? item.paid_by_name ?? item.person_name ?? item.name}</td><td>{item.date ?? item.joined_on ?? item.status ?? item.base_currency}</td></tr>)}</tbody></table>
      </section>
    </Shell>
  );
}

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/login" element={<Login />} />
        <Route path="/" element={<Dashboard />} />
        <Route path="/imports" element={<Imports />} />
        <Route path="/members" element={<SimpleList title="Membership Timeline" path="/memberships/" />} />
        <Route path="/expenses" element={<SimpleList title="Expenses" path="/expenses/" />} />
        <Route path="/settlements" element={<SimpleList title="Settlements" path="/settlements/" />} />
      </Routes>
    </BrowserRouter>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
